### ISSUE TITLE
导入Excel数据到数据库的时候有多个sheet如何处理

### ISSUE THREAD

**Issue by Chris-playground** [haoyanbing/easy-excel-demo#1]
请问我的Excel模板有多个sheet页，定义实体类的时候是定义到一个里面还是定义到多个里面，如何使用

**Comment by haoyanbing** [comment]
如果多个Sheet里面的数据是一致的，是可以一次读取多个Sheet的，只需要定义一个实体类，具体可以参考官方文档https://www.yuque.com/easyexcel/doc/read

我这里找到官方的示例，供参考：
`// 读取全部sheet`
`// 这里需要注意 DemoDataListener的doAfterAllAnalysed 会在每个sheet读取完毕后调用一次。然后所有sheet都会往同一个DemoDataListener里面写`
`EasyExcel.read(fileName, DemoData.class, new DemoDataListener()).doReadAll();`

**Comment by Chris-Arith** [comment]
你好，两个蛇毒sheet页是不同的数据，需要分别读取，官方的文档我看过了，有点疑问，方便加一下微信请教一下吗，谢谢！微信：ProfessionalBugMaker



---原始邮件---
发件人: "haoyanbing"<notifications@github.com&gt;
发送时间: 2020年7月23日(周四) 晚上7:16
收件人: "haoyanbing/easy-excel-demo"<easy-excel-demo@noreply.github.com&gt;;
抄送: "Chris-Arith"<2011578668@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [haoyanbing/easy-excel-demo] 导入Excel数据到数据库的时候有多个sheet如何处理 (#1)




 
如果多个Sheet里面的数据是一致的，是可以一次读取多个Sheet的，只需要定义一个实体类，具体可以参考官方文档https://www.yuque.com/easyexcel/doc/read
 
我这里找到官方的示例，供参考：
 // 读取全部sheet // 这里需要注意 DemoDataListener的doAfterAllAnalysed 会在每个sheet读取完毕后调用一次。然后所有sheet都会往同一个DemoDataListener里面写 EasyExcel.read(fileName, DemoData.class, new DemoDataListener()).doReadAll();

**Comment by haoyanbing** [comment]
您好，如果两个sheet的内容不一样，可以这样读取，下面代码摘自官方文档，供参考：
```java
        // 读取部分sheet
        fileName = TestFileUtil.getPath() + "demo" + File.separator + "demo.xlsx";
        ExcelReader excelReader = null;
        try {
            excelReader = EasyExcel.read(fileName).build();

            // 这里为了简单 所以注册了 同样的head 和Listener 自己使用功能必须不同的Listener
            ReadSheet readSheet1 =
                EasyExcel.readSheet(0).head(DemoData.class).registerReadListener(new DemoDataListener()).build();
            ReadSheet readSheet2 =
                EasyExcel.readSheet(1).head(DemoData.class).registerReadListener(new DemoDataListener()).build();
            // 这里注意 一定要把sheet1 sheet2 一起传进去，不然有个问题就是03版的excel 会读取多次，浪费性能
            excelReader.read(readSheet1, readSheet2);
        } finally {
            if (excelReader != null) {
                // 这里千万别忘记关闭，读的时候会创建临时文件，到时磁盘会崩的
                excelReader.finish();
            }
        }
```
里面readSheet(0)、readSheet(1)就是分别读取不同的Sheet的数据，里面的DeamData就是实体，两次可以传不同的实体，应该就能实现你的需求了。

**Comment by Chris-playground** [comment]
好的😄还有一个问题，我导入数据的时候用户下载模板填写后上传，是先上传到服务器上然后我去读取，还是可以通过流的方式直接读取，我试了用流的方式直接读取，能获取到流，但是直接就跳出去了，读取不到，您有试过用流读取吗？



---原始邮件---
发件人: "haoyanbing"<notifications@github.com&gt;
发送时间: 2020年7月23日(周四) 晚上8:11
收件人: "haoyanbing/easy-excel-demo"<easy-excel-demo@noreply.github.com&gt;;
抄送: "Chris-Arith"<2011578668@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [haoyanbing/easy-excel-demo] 导入Excel数据到数据库的时候有多个sheet如何处理 (#1)




 
您好，如果两个sheet的内容不一样，可以这样读取，下面代码摘自官方文档，供参考：
         // 读取部分sheet         fileName = TestFileUtil.getPath() + "demo" + File.separator + "demo.xlsx";         ExcelReader excelReader = null;         try {             excelReader = EasyExcel.read(fileName).build();             // 这里为了简单 所以注册了 同样的head 和Listener 自己使用功能必须不同的Listener             ReadSheet readSheet1 =                 EasyExcel.readSheet(0).head(DemoData.class).registerReadListener(new DemoDataListener()).build();             ReadSheet readSheet2 =                 EasyExcel.readSheet(1).head(DemoData.class).registerReadListener(new DemoDataListener()).build();             // 这里注意 一定要把sheet1 sheet2 一起传进去，不然有个问题就是03版的excel 会读取多次，浪费性能             excelReader.read(readSheet1, readSheet2);         } finally {             if (excelReader != null) {                 // 这里千万别忘记关闭，读的时候会创建临时文件，到时磁盘会崩的                 excelReader.finish();             }         }

**Comment by haoyanbing** [comment]
我是这样读取的，用 MultipartFile file 获取文件，然后通过 file.getInputStream() 来获取 InputStream 读取内容
